{{- include "message" .  }}
{{- if .Values.global.storage.pvc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2GI
  volumeMode: Filesystem
{{- end }}