{{- include "message" .  }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: '{{ .Release.Name }}-redis-insight'
  labels:
    {{- include "app.labels" . | indent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    link.argocd.argoproj.io/external-link: 'https://{{- include "host.name" . }}'
spec:
  host: '{{- include "host.name" . }}'
  to:
    kind: Service
    name: '{{ .Release.Name }}-redis-insight'
    weight: 100
  port:
    targetPort: {{ .Values.global.service.port }}
{{- if .Values.global.route.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}

