{{- include "message" .  }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: redis-browser
  labels:
    {{- include "app.labels" . | indent 4 }}
spec:
  host: '{{- include "host.name" . }}'
  to:
    kind: Service
    name: '{{ .Release.Name }}'
    weight: 100
  port:
    targetPort: {{ .Release.Name }}
{{- if .Values.global.route.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}

