{{- include "message" .  }}
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Release.Name }}'
  labels:
    {{- include "app.labels" . | indent 4 }}
spec:
  ports:
    - name: {{ .Release.Name }}
      protocol: TCP
      port: {{ .Values.global.service.port }}
      targetPort: {{ .Values.global.service.port }}
  type: ClusterIP
  selector:
    {{- include "selector.labels" . | indent 4 }}